version: "3.3"
services:
  fastapi-ml:
    container_name: fastapi-ml
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # set true only if INSTALL_DEV is unset in the environment.
        INSTALL_DEV: ${INSTALL_DEV-true} 
    ports:
      - 9000:9000      
